version: '3.3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - file_manager:/var/lib/postgresql/data
    networks:
      - network1

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - ${MINIO_PORT}:9000
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_ACCESS_KEY}
    volumes:
      - file_manager:/data
      - file_manager:/root/.minio
    command: server /data
    networks:
      network1:
        ipv4_address: ${MINIO_HOST}

  configure-minio:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://${MINIO_HOST}:${MINIO_PORT} minioadmin minioadmin;
      exit 0;
      "
    networks:
      network1:
        ipv4_address: ${MINIO_HOST_ALT}

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - file_manager:/data
    networks:
      - network1

  app:
    container_name: rails_server
    image: rails_server:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - db
      - minio
      - redis
    environment:
      RAILS_WEB_CONTAINER: true
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}
      REDIS_URL: redis://redis:${REDIS_PORT}/1
    networks:
      - network1

  sidekiq:
    container_name: rails_sidekiq
    image: rails_sidekiq:latest
    build:
      context: .
      dockerfile: Dockerfile.sidekiq
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - minio
      - redis
      - app
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}
      REDIS_URL: redis://redis:${REDIS_PORT}/1
    networks:
      - network1

volumes:
  file_manager:

networks:
 network1:
  ipam:
    config:
    - subnet: ${CUSTOM_NETWORK_SUBNET}
