version: '3.3'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - file_manager:/var/lib/mysql
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: 'my_access_key'
      MINIO_ROOT_PASSWORD: 'my_secret_key'
    volumes:
      - file_manager:/data
      - file_manager:/root/.minio
    command: server /data
volumes:
  file_manager:
