version: '3.3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - file_manager:/var/lib/postgresql/data
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: 'my_access_key'
      MINIO_ROOT_PASSWORD: 'my_secret_key'
    volumes:
      - file_manager:/data
      - file_manager:/root/.minio
    command: server /data
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - file_manager:/data
volumes:
  file_manager:
