version: '3.3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - file_manager:/var/lib/postgresql/data
    networks:
      - network1
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - ${MINIO_PORT}:9000
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_ACCESS_KEY}
    volumes:
      - file_manager:/data
      - file_manager:/root/.minio
    command: server /data
    networks:
      - network1
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - file_manager:/data
    networks:
      - network1
  app:
    container_name: rails_server
    image: rails_server:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - db
      - minio
      - redis
    environment:
      RAILS_WEB_CONTAINER: true
      DB_HOST: db
      REDIS_URL: redis://redis:${REDIS_PORT}/1
    networks:
      - network1
  sidekiq:
    container_name: rails_sidekiq
    image: rails_sidekiq:latest
    build:
      context: .
      dockerfile: Dockerfile.sidekiq
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - minio
      - redis
      - app
    environment:
      DB_HOST: db
      REDIS_URL: redis://redis:${REDIS_PORT}/1
    networks:
      - network1
volumes:
  file_manager:
networks:
  network1:
