---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/sign_up":
    post:
      summary: Sign Up
      tags:
      - Auth
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              examples:
                created:
                  value:
                    success: true
                    data:
                      email: email@example.com
                      fname: John
                      lname: Doe
                    meta: {}
        '422':
          description: unprocessable_entity
          content:
            application/json:
              examples:
                parameter_missing:
                  value:
                    success: false
                    error:
                    - "<attribute_name>": cannot be blank
                email_invalid:
                  value:
                    success: false
                    error:
                    - email: is invalid
                email_exists:
                  value:
                    success: false
                    error: Parameter missing
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    fname:
                      type: string
                    lname:
                      type: string
                required:
                - email
                - password
                - fname
                - lname
              require:
              - user
  "/api/v1/auth/sign_in":
    post:
      summary: Sign In
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: ok
          content:
            application/json:
              examples:
                ok:
                  value:
                    success: true
                    data:
                      email: email@example.com
                      fname: John
                      lname: Doe
                    meta:
                      token: abcde
                      refresh_token: abcde
        '404':
          description: not_found
          content:
            application/json:
              examples:
                not_found:
                  value:
                    success: false
                    error: Not found
        '400':
          description: unprocessable_entity
          content:
            application/json:
              examples:
                parameter_missing:
                  value:
                    success: false
                    error: Parameter missing
        '401':
          description: unauthorized
          content:
            application/json:
              examples:
                unauthorized:
                  value:
                    success: false
                    error: Email or Password is invalid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/auth/refresh_token":
    post:
      summary: Refresh token
      tags:
      - Auth
      parameters:
      - name: Authorization
        in: header
        required: true
        description: Token
        schema:
          type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              examples:
                ok:
                  value:
                    success: true
                    data: []
                    meta:
                      token: abcde
        '401':
          description: unauthorized
          content:
            application/json:
              examples:
                invalid_token:
                  value:
                    success: false
                    error: Invalid Token
                unauthorized:
                  value:
                    success: false
                    error: Unauthorized
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1
