---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/sign_up":
    post:
      summary: Sign Up
      tags:
      - Auth
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              examples:
                example_0:
                  value:
                    success: true
                    data:
                      email: email@example.com
                      fname: John
                      lname: Doe
                    meta: {}
        '422':
          description: email exists
          content:
            application/json:
              examples:
                example_0:
                  value:
                    success: false
                    error: Parameter missing
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                fname:
                  type: string
                lname:
                  type: string
              required:
              - email
              - password
              - fname
              - lname
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1
